services:
  # Redis Yapılandırması
  redis:
    image: redis:7-alpine
    container_name: nosql-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data

  # MongoDB Yapılandırması
  mongodb:
    image: mongo:7
    container_name: nosql-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: nosqllab
    volumes:
      - mongodb-data:/data/db

  # Hazelcast Yapılandırması (Client 3.12 ile uyumlu olması için)
  hazelcast:
    image: hazelcast/hazelcast:3.12
    container_name: nosql-hazelcast
    ports:
      - "5701:5701"
    environment:
      JAVA_OPTS: "-Dhazelcast.local.publicAddress=127.0.0.1:5701"
    volumes:
      - hazelcast-data:/data

# Buradaki isimler yukarıdaki 'volumes' kısımlarıyla birebir aynı olmalıdır
volumes:
  redis-data:
  mongodb-data:
  hazelcast-data: